# Generated by Django 3.0.8 on 2020-07-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=13),
        ),
    ]
